export default {
  name: 'tourPackage',
  title: 'Tour Package',
  type: 'document',
  groups: [
    { name: 'overview', title: '1. Overview & Pricing', default: true },
    { name: 'itinerary', title: '2. Day-by-Day Itinerary' },
    { name: 'inclusions', title: '3. Inclusions & Transport' },
    { name: 'media', title: '4. Photos & Media' },
    { name: 'seasonal', title: '5. Monthly Rates' },
  ],
  fields: [
    {
      name: 'title',
      title: 'Package Title (e.g. Tropical Andaman Island Package)',
      type: 'string',
      group: 'overview',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Package URL Slug',
      type: 'slug',
      group: 'overview',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'packageId',
      title: 'Package ID',
      type: 'string',
      group: 'overview',
      description: 'Used for system matching (e.g. andaman-6n7d, pkg-1)',
    },
    {
      name: 'destination',
      title: 'Destination Name (e.g. Andaman Islands, Kashmir, Sikkim)',
      type: 'string',
      group: 'overview',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'duration',
      title: 'Duration (e.g. 6 Nights / 7 Days)',
      type: 'string',
      group: 'overview',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'price',
      title: 'Base Price per Person (e.g. ₹38,990)',
      type: 'string',
      group: 'overview',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'originalPrice',
      title: 'Original / Strikethrough Price (Optional, e.g. ₹45,000)',
      type: 'string',
      group: 'overview',
    },
    {
      name: 'shortDescription',
      title: 'Summary / Short Description',
      type: 'text',
      group: 'overview',
      rows: 3,
    },
    {
      name: 'stayBreakdown',
      title: 'Stay Breakdown (e.g. Port Blair — 4N | Havelock Island — 1N | Neil Island — 1N)',
      type: 'string',
      group: 'overview',
    },
    {
      name: 'featured',
      title: 'Featured Package (Show on Homepage Top Departures)',
      type: 'boolean',
      group: 'overview',
      initialValue: false,
    },
    {
      name: 'isAvailable',
      title: 'Available for Booking',
      type: 'boolean',
      group: 'overview',
      initialValue: true,
    },
    {
      name: 'rating',
      title: 'Customer Star Rating (e.g. 4.9)',
      type: 'number',
      group: 'overview',
      initialValue: 4.8,
    },
    {
      name: 'reviewsCount',
      title: 'Number of Reviews (e.g. 184)',
      type: 'number',
      group: 'overview',
      initialValue: 100,
    },
    {
      name: 'nextDate',
      title: 'Next Departure Tag (e.g. Available on Booking or Upcoming Sunday)',
      type: 'string',
      group: 'overview',
      initialValue: 'Available on Booking',
    },
    {
      name: 'image',
      title: 'Cover Image',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt text' }],
    },
    {
      name: 'imageUrl',
      title: 'Fallback Image Path (e.g. /images/hero_andaman_1783678485939.png)',
      type: 'string',
      group: 'media',
    },
    {
      name: 'gallery',
      title: 'Tour Photo Gallery',
      type: 'array',
      group: 'media',
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [{ name: 'alt', type: 'string', title: 'Alt text' }],
        },
      ],
    },
    {
      name: 'galleryUrls',
      title: 'Fallback Gallery Image Paths',
      type: 'array',
      group: 'media',
      of: [{ type: 'string' }],
    },
    {
      name: 'videoUrl',
      title: 'Video Embed URL (YouTube embed link)',
      type: 'string',
      group: 'media',
    },
    {
      name: 'highlights',
      title: 'Tour Highlights (Bullet points)',
      type: 'array',
      group: 'overview',
      of: [{ type: 'string' }],
    },
    {
      name: 'itinerary',
      title: 'Day-by-Day Itinerary Schedule',
      type: 'array',
      group: 'itinerary',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'day', title: 'Day Number (e.g. 1)', type: 'number' },
            { name: 'title', title: 'Day Title (e.g. Arrival & Cellular Jail)', type: 'string' },
            { name: 'desc', title: 'Day Description / Activities', type: 'text', rows: 3 },
            { name: 'spots', title: 'Spots Visited (List)', type: 'array', of: [{ type: 'string' }] },
            { name: 'meals', title: 'Meals Included (e.g. Lunch & Dinner)', type: 'string' },
          ],
        },
      ],
    },
    {
      name: 'transport',
      title: 'Transportation Information',
      type: 'object',
      group: 'inclusions',
      fields: [
        { name: 'mode', title: 'Mode of Travel', type: 'string' },
        { name: 'pickup', title: 'Pickup & Drop Point', type: 'string' },
        { name: 'vehicle', title: 'Vehicle Type', type: 'string' },
        { name: 'details', title: 'Additional Notes', type: 'text', rows: 2 },
      ],
    },
    {
      name: 'accommodation',
      title: 'Hotel & Stay Details',
      type: 'object',
      group: 'inclusions',
      fields: [
        { name: 'category', title: 'Hotel Category (e.g. 3-Star Deluxe AC)', type: 'string' },
        { name: 'description', title: 'Night Breakdown', type: 'string' },
        { name: 'meals', title: 'Meal Plan (e.g. MAP / Breakfast & Dinner)', type: 'string' },
        { name: 'features', title: 'Key Amenities', type: 'array', of: [{ type: 'string' }] },
      ],
    },
    {
      name: 'pricingDetails',
      title: 'Inclusions & Exclusions',
      type: 'object',
      group: 'inclusions',
      fields: [
        { name: 'perHead', title: 'Per Head Tag', type: 'string' },
        { name: 'groupDiscount', title: 'Group Discount Info', type: 'string' },
        { name: 'inclusions', title: 'What is Included (List)', type: 'array', of: [{ type: 'string' }] },
        { name: 'exclusions', title: 'What is Excluded (List)', type: 'array', of: [{ type: 'string' }] },
      ],
    },
    {
      name: 'seasonalPricing',
      title: 'Dynamic Monthly Rate Breakdown (₹ per head)',
      type: 'object',
      group: 'seasonal',
      fields: [
        { name: 'January', title: 'January Rate (₹)', type: 'number' },
        { name: 'February', title: 'February Rate (₹)', type: 'number' },
        { name: 'March', title: 'March Rate (₹)', type: 'number' },
        { name: 'April', title: 'April Rate (₹)', type: 'number' },
        { name: 'May', title: 'May Rate (₹)', type: 'number' },
        { name: 'June', title: 'June Rate (₹)', type: 'number' },
        { name: 'July', title: 'July Rate (₹)', type: 'number' },
        { name: 'August', title: 'August Rate (₹)', type: 'number' },
        { name: 'September', title: 'September Rate (₹)', type: 'number' },
        { name: 'October', title: 'October Rate (₹)', type: 'number' },
        { name: 'November', title: 'November Rate (₹)', type: 'number' },
        { name: 'December', title: 'December Rate (₹)', type: 'number' },
      ],
    },
    {
      name: 'pricingNote',
      title: 'Pricing Footnote / Important Advisory',
      type: 'string',
      group: 'seasonal',
    },
  ],
  preview: {
    select: {
      title: 'title',
      destination: 'destination',
      duration: 'duration',
      price: 'price',
      featured: 'featured',
      media: 'image',
    },
    prepare(selection: any) {
      const { title, destination, duration, price, featured, media } = selection;
      return {
        title: `${featured ? '⭐ ' : ''}${title || 'Untitled Package'}`,
        subtitle: `${destination || ''} • ${duration || ''} • ${price || ''}`,
        media,
      };
    },
  },
};
